[versions]
agp = "8.6.0"
kotlin = "2.0.20"
googleKsp = "2.0.20-1.0.25"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.2"
constraintlayout = "2.1.4"
corouines = "1.8.1"
tuiutils = "1.0.9"
glide = "4.16.0"
swiperefreshlayout = "1.1.0"
tmediaplayer = "1.4.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "corouines" }
coroutines-core-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "corouines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "corouines" }
tuiutils = { group = "io.github.tans5", name = "tuiutils", version.ref = "tuiutils"}
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide"}
glide-codegen-kapt = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
glide-codegen-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name="swiperefreshlayout",  version.ref="swiperefreshlayout"}
tmediaplayer = { group = "io.github.tans5", name = "tmediaplayer", version.ref = "tmediaplayer" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
googleKsp = { id = "com.google.devtools.ksp", version.ref = "googleKsp" }

